# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='omanikud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('omaniku_nr', models.IntegerField(default=0)),
                ('omanik_nimi', models.CharField(max_length=255)),
                ('omatud_raamatu_nr', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='raamatud',
            fields=[
                ('raamatu_nr', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('raamatu_nimi', models.CharField(max_length=255)),
                ('raamatu_lehti', models.IntegerField(default=0)),
                ('omanikud', models.ManyToManyField(to='app.omanikud')),
            ],
        ),
    ]
